# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

run:
  go: "1.26"
  build-tags: []

issues:
  exclude-dirs:
    - proto/gen

formatters:
  enable:
    - gci
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      max-len: 120
