package ttoapi

//go:generate echo [ttoapi] converting from Swagger to OpenAPI...
//go:generate npx swagger2openapi@v7.0.8 01-original.json --outfile 02-converted.yaml --yaml

//go:generate echo [ttoapi] generating coordinate overlay...
//go:generate python3 generate-coordinate-overlay.py ../../../docs/object-coordinates-history-api-v2.md coordinate-overlay.yaml

//go:generate echo [ttoapi] applying coordinate overlay...
//go:generate sh -c "go tool -modfile ../../../tools/go.mod openapi-overlay apply coordinate-overlay.yaml 02-converted.yaml > 03-coordinate-overlayed.yaml"

//go:generate echo [ttoapi] applying standard overlay...
//go:generate sh -c "go tool -modfile ../../../tools/go.mod openapi-overlay apply overlay.yaml 03-coordinate-overlayed.yaml > 04-overlayed.yaml"

//go:generate echo [ttoapi] generating code...
//go:generate go tool -modfile ../../../tools/go.mod oapi-codegen -config config.yaml 04-overlayed.yaml
