name: Release

on:
  push:
    branches: [main]

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Build
        run: ./tools/mage build

      - name: Run Go Semantic Release
        uses: go-semantic-release/action@v1
        with:
          allow-initial-development-versions: true
          hooks: goreleaser
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
